### ISSUE TITLE
不能建立

### ISSUE THREAD

**Issue by honqiang** [hamlinzheng/docker-zerotier-server#2]
1 error occurred:
	* Status: The command '/bin/sh -c apk add --no-cache curl g++ &&     ip=`curl https://ip.3322.net` && addr=${ip}/9993 && identity=`cat /var/lib/zerotier-one/identity.public` &&     echo "**************************************************************************" &&     echo "addr: ${addr}" && echo "identity: ${identity}" &&     curl https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/refs/tags/${ZEROTIER_VERSION} --output /tmp/ZeroTierOne.tar.gz &&     cd /tmp && tar fxz /tmp/ZeroTierOne.tar.gz &&     mv /tmp/ZeroTierOne-* /tmp/ZeroTierOne &&     cd /tmp/ZeroTierOne/attic/world/ &&     sed -i '/roots.push_back/d' ./mkworld.cpp && sed -i '/roots.back()/d' ./mkworld.cpp &&     sed -i '85i roots.push_back(World::Root());' ./mkworld.cpp &&     sed -i '86i roots.back().identity = Identity(\"'"$identity"'\");' ./mkworld.cpp &&     sed -i '87i roots.back().stableEndpoints.push_back(InetAddress(\"'"$addr"'\"));' ./mkworld.cpp &&     sh ./build.sh && ./mkworld && mv ./world.bin /var/lib/zerotier-one/planet &&     apk del curl g++ && rm -rf /var/cache/apk/* && rm -rf /root/.cache && rm -rf /tmp/*' returned a non-zero code: 2, Code: 2

**Comment by hamlinzheng** [comment]
Due to a certificate problem with the alpine download source, it has been fixed: db4a2b3882fb0c394cf70deeb1e89289a155c92f
